### ISSUE TITLE
tinyint/boolean behavior

### ISSUE THREAD

**Issue by evert** [coreyarms/mysql-types-generator#1]
With libraries such as mysql2, a `BOOLEAN` field is sent over the as a `TINYINT` (I believe they are aliases), and so the actual types that mysql2 will emit for these is `number`, not `boolean`.

It's useful for us to actually type these as number, because we want to make sure that for our outgoing types (past the 'service layer' these are real booleans).

Is it possible to override the behavior that assumes tinyints are booleans?

**Comment by coreyarms** [comment]
I assumed all `TINYINT` are boolean in the first place because I basically never use `TINYINT` in my databases except for boolean, and my typical `knex` config has a rule to automatically convert them to boolean in query results.

There is an `overrides` parameter in the config, but you would need to specify every `TINYINT` column that you want to override:
```
overrides: [
  {
    tableName: 'my_table',
    columnName: 'my_actual_tinyint_column',
    columnType: 'int', // this will set the Typescript type as Number 
  }
]
```

Otherwise I would be OK with creating another config parameter to do the opposite behaviour- treat all `TINYINT` as `number` and if you want `boolean` you need to specify it the config `overrides`

Do you have any better ideas? I'm open to anything.

**Comment by evert** [comment]
> I assumed all TINYINT are boolean in the first place because I basically never use TINYINT in my databases except for boolean, and my typical knex config has a rule to automatically convert them to boolean in query results.

Yeah this makes sense. You can actually narrow this down a bit further by looking for a `TINYINT(1)`, which I think is what MySQL automatically maps booleans to.

But yeah in my case i would love a simple flag, maybe something like `tinyintIsBool` ? If you want the 'happy path' to be for knex, default to `true`, but ofc I would default this to `false`.

Happy to implement this, lemme know!
